// kmexplorer/pages/index.vue
<template>
	<div class="km-home">
		<a href="http://karaokes.moe/">
			<img class="km-home--logo" :src="require('~/assets/km-logo.png')"/>
		</a>
		<h1 class="title">{{ explorerHost }}</h1>
		<h2 class="subtitle">Explore! Find! Sing!</h2>
		<ul class="km-home--stats">
			<li key="karas">
				<div class="km-home--stats--link">
					<strong>{{count.karas>0 ? count.karas : '-'}}</strong>
					<span>{{$tc("stats.karaokes", count.karas)}}</span>
				</div>
			</li>
			<li key="serie">
				<div class="km-home--stats--link">
					<strong>{{count.series>0 ? count.series : '-'}}</strong>
					<span>{{$tc("kara.tagtypes.series", count.series)}}</span>
				</div>
			</li>
			<li key="singer">
				<div class="km-home--stats--link">
					<strong>{{count.singers>0 ? count.singers : '-'}}</strong>
					<span>{{$tc("kara.tagtypes.singers", count.singers)}}</span>
				</div>
			</li>
			<li key="creator">
				<div class="km-home--stats--link">
					<strong>{{count.creators>0 ? count.creators : '-'}}</strong>
					<span>{{$tc("kara.tagtypes.creators", count.creators)}}</span>
				</div>
			</li>
			<li key="language">
				<div class="km-home--stats--link">
					<strong>{{count.languages>0 ? count.languages : '-'}}</strong>
					<span>{{$tc("kara.tagtypes.langs", count.languages)}}</span>
				</div>
			</li>
			<li key="author">
				<div class="km-home--stats--link">
					<strong>{{count.authors>0 ? count.authors : '-'}}</strong>
					<span>{{$tc("kara.tagtypes.authors", count.authors)}}</span>
				</div>
			</li>
			<li key="songwriter">
				<div class="km-home--stats--link">
					<strong>{{count.songwriters>0 ? count.songwriters : '-'}}</strong>
					<span>{{$tc("kara.tagtypes.songwriters", count.songwriters)}}</span>
				</div>
			</li>
			<li key="mediasize">
				<span>{{$t("stats.media_size")}}</span> :
				<strong>{{count.mediasize !== 0 ? count.mediasize : '-'}}</strong>
			</li>
			<li class="km-home--stats--wide" key="lastGeneration">
				<span>{{$t("stats.last_generation")}}</span> :
				<strong>{{count.lastGeneration ? new Date(count.lastGeneration).toLocaleString() : '-'}}</strong>
			</li>
			<li class="km-home--stats--wide" key="duration">
				<span>{{$t("stats.all_duration")}} :</span>
				<strong>{{count.duration ? count.duration : '-'}}</strong>
			</li>
		</ul>
	</div>
</template>

<script lang="ts">
	import Vue from "vue";
	import prettyBytes from 'pretty-bytes';
	import duration from '~/assets/date';

	export default Vue.extend({
		data() {
			return {
				explorerHost: process.env.EXPLORER_HOST,
				count: {
					singers: 0,
					creators: 0,
					languages: 0,
					authors: 0,
					songwriters: 0,
					series: 0,
					karas: 0,
					duration: 0,
					mediasize: 0
				}
			};
		},
		async asyncData({$axios, app}) {
			let result = await $axios.get("/api/karas/stats");
			let count = result.data;
			if (count.mediasize) count.mediasize = prettyBytes(Number(count.mediasize));
			if (count.mediasize) {
				const durationArray = duration(count.duration);
				let returnString = '';
				if (durationArray[0] !== 0) returnString += `${durationArray[0]} ${app.i18n.t("duration.days")} `;
				if (durationArray[1] !== 0) returnString += `${durationArray[1]} ${app.i18n.t("duration.hours")} `;
				if (durationArray[2] !== 0) returnString += `${durationArray[2]} ${app.i18n.t("duration.minutes")} `;
				if (durationArray[3] !== 0) returnString += `${durationArray[3]} ${app.i18n.t("duration.seconds")} `;
				count.duration = returnString;
			}
			count.lastGeneration = (await $axios.get("/api/karas/lastUpdate")).data;
			return {count: count};
		},
		head() {
			return {
				title: this.$t('titles.home') as string
			}
		}
	});
</script>
<style scoped lang="scss">
	.km-home {
		display: flex;
		flex-direction: column;
		align-items: center;

		.km-home--logo {
			max-width: 600px;
		}

		.km-home--stats {
			max-width: 600px;
			padding: 0;
			margin: auto;
			display: flex;
			flex-direction: row;
			flex-wrap: wrap;
			list-style: none;

			.km-home--stats--link {
				cursor: pointer;
			}

			li {
				padding: 0.5em;
				width: calc(50% - 1em);
				background: #26aacc;
				color: #fff;
				margin: 0.5em;
				border-radius: 0.25em;
			}

			.km-home--stats--wide {
				width: 100%;
			}
		}
	}
</style>

// react_site/pages/index.js
import React from 'react'
import { i18n, withNamespaces } from '../i18n'
import i18nRouterPush from '../utils/i18nRouterPush'
import Head from 'next/head'
import axios from 'axios'
import Pagination from '../components/Pagination';
import DedicatedTagtList from '../components/DedicatedTagList';
import tagsMap from '../components/tagsMap.js';
import querystring from 'querystring';
import FilterTools from '../utils/filterTools';
import duration from '../utils/date';
const filterTools = new FilterTools();

class Page extends React.Component {
	static async getInitialProps({ req, query, res }) {

		let namespacesRequired = ['common', 'tag'];

		return { namespacesRequired };
	}

	constructor (props) {
		super(props)
		this.state = {}
	}


	render() {

		var count = {
			singer:0,
			songtype:0,
			creator:0,
			language:0,
			author:0,
			misc:0,
			group:0,
			songwriter:0,
			serie:0,
			karas:0,
			duration:0
		};
		if(this.props.stats)
		{
			count.singer = this.props.stats.singers;
			count.creator = this.props.stats.creators;
			count.language = this.props.stats.languages;
			count.author = this.props.stats.authors;
			count.songwriter = this.props.stats.songwriters;
			count.serie = this.props.stats.series;
			count.karas = this.props.stats.karas;
			count.duration = this.props.stats.duration;
			count.lastGeneration = this.props.stats.lastGeneration;
		}
		if(this.props.tags)
		{
			for (let i in this.props.tags)
			{
				let t = this.props.tags[i];
				if(t.code==='misc') count.misc++;
				if(t.code==='songtype') count.songtype++;
				if(t.code==='group') count.group++;
			}
		}

		return (
			<div>
				<Head>
					<title key="title">{i18n.t('sitename')} - {i18n.t('category.home')}</title>
				</Head>

				<div className="km-home">
					<img className="km-home--logo" src={require('../static/images/km-logo.png')} />

					<ul className="km-home--stats">
						<li key="karas"><strong>{count.karas>0 ? count.karas : '-'}</strong> <span>{i18n.t("category.karas")}</span></li>
						<li key="serie"><strong>{count.serie>0 ? count.serie : '-'}</strong> <span>{i18n.t("category.series")}</span></li>
						<li key="singer"><strong>{count.singer>0 ? count.singer : '-'}</strong> <span>{i18n.t("category.singers")}</span></li>
						<li key="creator"><strong>{count.creator>0 ? count.creator : '-'}</strong> <span>{i18n.t("category.creators")}</span></li>
						<li key="language"><strong>{count.language>0 ? count.language : '-'}</strong> <span>{i18n.t("category.languages")}</span></li>
						<li key="author"><strong>{count.author>0 ? count.author : '-'}</strong> <span>{i18n.t("category.authors")}</span></li>
						<li key="misc"><strong>{count.misc>0 ? count.misc : '-'}</strong> <span>{i18n.t("category.tags")}</span></li>
						<li key="songwriter"><strong>{count.songwriter>0 ? count.songwriter : '-'}</strong> <span>{i18n.t("category.songwriters")}</span></li>
						<li className="km-home--stats--wide" key="lastGeneration"><span>{i18n.t("stats.last_generation")}</span> : <strong>{new Date(count.lastGeneration).toLocaleString()}</strong></li>
						<li className="km-home--stats--wide" key="duration"><span>{i18n.t("stats.all_duration")} :</span> <strong>{count.duration>0 ? duration(count.duration) : '-'}</strong></li>
					</ul>
				</div>
			</div>
		);
	}
}

export default withNamespaces(['common','tag'])(Page)
